shared: &shared
  adapter: <%= Settings.database.adapter %>
  database: <%= Settings.database.name %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  port: <%= Settings.database.port %>
  host: '<%= Rails.application.credentials.dig(:database, :host) %>'
  reconnect: <%= Settings.database.reconnect %>
  encoding: <%= Settings.database.encoding %>

development:
  <<: *shared
  host: '<%= Settings.database.host %>'
  password: <%= Settings.database.password %>
  username: <%= Settings.database.username %>

test:
  <<: *shared
  host: '<%= Settings.database.host || Rails.application.credentials.dig(:database, :host) %>'
  database: <%= Settings.database.name %>_test<%= (ENV['TEST_ENV_NUMBER'] == "1") ? "" : ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *shared

production:
  <<: *shared
